services:
  pg_parquet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE_OS: ${BASE_IMAGE_OS}
        BASE_IMAGE_OS_VERSION: ${BASE_IMAGE_OS_VERSION}
        RUSTC_VERSION: ${RUSTC_VERSION}
        DEFAULT_PG_MAJOR: ${DEFAULT_PG_MAJOR}
    container_name: pg_parquet
    entrypoint: ["/workspace/.devcontainer/scripts/pg_parquet-entrypoint.sh"]
    working_dir: /workspace
    healthcheck:
      test: ["CMD", "curl","pg_parquet:9999"]
      interval: 60s
      timeout: 10s
      retries: 6
    volumes:
      - ..:/workspace
      # - ${USERPROFILE}${HOME}/.ssh:/home/rust/.ssh:ro
      # - ${USERPROFILE}${HOME}/.ssh/known_hosts:/home/rust/.ssh/known_hosts:rw
      # - ${USERPROFILE}${HOME}/.gitconfig:/home/rust/.gitconfig:ro
      # - ${USERPROFILE}${HOME}/.aws:/home/rust/.aws:rw
      # - ${USERPROFILE}${HOME}/.azure:/home/rust/.azure:rw
      # - ${USERPROFILE}${HOME}/.config/gcloud:/home/rust/.config/gcloud:rw
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
    depends_on:
      - minio
      - azurite
      - webdav
      - fake-gcs-server

  minio:
    image: ${MINIO_IMAGE}
    entrypoint: ["/entrypoint.sh"]
    container_name: minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://minio:9000"]
      interval: 6s
      timeout: 2s
      retries: 3
    volumes:
        - ./scripts/minio-entrypoint.sh:/entrypoint.sh
    env_file:
      - .env

  azurite:
    image: ${AZURITE_IMAGE}
    container_name: azurite
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./scripts/azurite-entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "azurite", "10000"]
      interval: 6s
      timeout: 2s
      retries: 3

  webdav:
    image: ${WEBDAV_IMAGE}
    container_name: webdav
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./scripts/webdav-entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "webdav", "8080"]
      interval: 6s
      timeout: 2s
      retries: 3

  fake-gcs-server:
    image: ${FAKE_GCS_IMAGE}
    container_name: fake-gcs-server
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./scripts/fake-gcs-entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "fake-gcs-server", "4443"]
      interval: 6s
      timeout: 2s
      retries: 3
