name: Build and tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_NAME: crunchydata
  REGISTRY: ghcr.io

jobs:
  build-image:
    strategy:
      matrix:
        base_image_os: [ '{"name": "almalinux", "version": "8"}', '{"name": "almalinux", "version": "9"}', '{"name": "almalinux", "version": "10"}', '{"name": "debian", "version": "bookworm"}', '{"name": "debian", "version": "trixie"}', '{"name": "debian", "version": "forky"}' ]
        runs_on: [ 'ubuntu-22.04', 'ubuntu-22.04-arm' ]
        include:
          - runs_on: ubuntu-22.04
            arch: x86_64
          - runs_on: ubuntu-22.04-arm
            arch: aarch64

    runs-on: ${{ matrix.runs_on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse base image os and version
        id: parse-base-image
        run: |
          echo "base_image_os=$(echo '${{ matrix.base_image_os }}' | jq -r '.name')" >> $GITHUB_OUTPUT
          echo "base_image_os_version=$(echo '${{ matrix.base_image_os }}' | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Build and push image for ${{ steps.parse-base-image.outputs.base_image_os }}:${{ steps.parse-base-image.outputs.base_image_os_version }} on ${{ matrix.arch }}
        id: build-and-push
        uses: ./.github/actions/build-and-push-image
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          org_name: ${{ env.ORG_NAME }}
          base_image_os: ${{ steps.parse-base-image.outputs.base_image_os }}
          base_image_os_version: ${{ steps.parse-base-image.outputs.base_image_os_version }}
          arch: ${{ matrix.arch }}


  build-and-test:
    needs: build-image
    strategy:
      matrix:
        postgres: [ 14, 15, 16, 17, 18 ]
        base_image_os: [ '{"name": "almalinux", "version": "8"}', '{"name": "almalinux", "version": "9"}', '{"name": "almalinux", "version": "10"}', '{"name": "debian", "version": "bookworm"}', '{"name": "debian", "version": "trixie"}', '{"name": "debian", "version": "forky"}' ]
        runs_on: [ 'ubuntu-22.04', 'ubuntu-22.04-arm' ]
        include:
          - runs_on: ubuntu-22.04
            arch: x86_64
          - runs_on: ubuntu-22.04-arm
            arch: aarch64

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4

      - name: Parse base image os and version
        id: parse-base-image
        run: |
          echo "base_image_os=$(echo '${{ matrix.base_image_os }}' | jq -r '.name')" >> $GITHUB_OUTPUT
          echo "base_image_os_version=$(echo '${{ matrix.base_image_os }}' | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Build and test on Postgres ${{ matrix.postgres }} with ${{ steps.parse-base-image.outputs.base_image_os }}:${{ steps.parse-base-image.outputs.base_image_os_version }} on ${{ matrix.arch }}
        uses: ./.github/actions/build-and-test
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: "${{ env.REGISTRY }}/${{ env.ORG_NAME }}/pg_parquet:${{ steps.parse-base-image.outputs.base_image_os }}-${{ steps.parse-base-image.outputs.base_image_os_version }}-${{ matrix.arch }}-${{ hashFiles('.devcontainer/Dockerfile') }}"
          postgres: ${{ matrix.postgres }}
          arch: ${{ matrix.arch }}
          base_image_os: ${{ steps.parse-base-image.outputs.base_image_os }}
          base_image_os_version: ${{ steps.parse-base-image.outputs.base_image_os_version }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
