name: Build and tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ORG_NAME: crunchydata
  REGISTRY: ghcr.io

jobs:
  build-image:
    strategy:
      matrix:
        base_image_os: [ 'almalinux', 'debian' ]
        runs_on: [ 'ubuntu-22.04', 'ubuntu-22.04-arm' ]
        include:
          - runs_on: ubuntu-22.04
            arch: x86_64
          - runs_on: ubuntu-22.04-arm
            arch: aarch64
          - base_image_os: almalinux
            base_image_os_version: 9
          - base_image_os: debian
            base_image_os_version: bookworm

    runs-on: ${{ matrix.runs_on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image for ${{ matrix.base_image_os }}:${{ matrix.base_image_os_version }} on ${{ matrix.arch }}
        id: build-and-push
        uses: ./.github/actions/build-and-push-image
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          org_name: ${{ env.ORG_NAME }}
          base_image_os: ${{ matrix.base_image_os }}
          base_image_os_version: ${{ matrix.base_image_os_version }}
          arch: ${{ matrix.arch }}


  build-and-test:
    needs: build-image
    strategy:
      matrix:
        postgres: [ 14, 15, 16, 17, 18 ]
        base_image_os: [ 'almalinux', 'debian' ]
        runs_on: [ 'ubuntu-22.04', 'ubuntu-22.04-arm' ]
        include:
          - runs_on: ubuntu-22.04
            arch: x86_64
          - runs_on: ubuntu-22.04-arm
            arch: aarch64
          - base_image_os: almalinux
            base_image_os_version: 9
          - base_image_os: debian
            base_image_os_version: bookworm

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and test on Postgres ${{ matrix.postgres }} with ${{ matrix.base_image_os }}:${{ matrix.base_image_os_version }} on ${{ matrix.arch }}
        uses: ./.github/actions/build-and-test
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: "${{ env.REGISTRY }}/${{ env.ORG_NAME }}/pg_parquet:${{ matrix.base_image_os }}-${{ matrix.base_image_os_version }}-${{ matrix.arch }}-${{ hashFiles('.devcontainer/Dockerfile') }}"
          postgres: ${{ matrix.postgres }}
          arch: ${{ matrix.arch }}
          base_image_os: ${{ matrix.base_image_os }}
          base_image_os_version: ${{ matrix.base_image_os_version }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
