name: CI lints and tests
on:
  push:
    branches:
      - "*"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79.0
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy, llvm-tools-preview

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.7"

      - name: Install grcov
        run: |
          cargo install grcov

      - name: Install PostgreSQL dependencies
        run: |
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config
          sudo apt-get -y install postgresql-16-postgis-3 libpq-dev postgresql-server-dev-16 postgresql-client-16

      - name: Install and configure pgrx
        run: |
          cargo install --locked cargo-pgrx@0.11.4
          cargo pgrx init --pg16 $(which pg_config)

      - name: Format and lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: |
          cargo pgrx test pg16 --runas postgres --pgdata /tmp/pgdata
        env:
          RUSTFLAGS: "-C instrument-coverage"
          RUST_TEST_THREADS: 1

      - name: Generate coverage report
        run: |
          grcov . \
            -s . \
            --binary-path ./target/debug/ \
            -t lcov \
            --ignore-not-existing \
            --keep-only 'src/**' \
            -o pg_parquet.lcov

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./pg_parquet.lcov
          flags: pgrxtests
          token: ${{ secrets.CODECOV_TOKEN }}
